name: acinonyx
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - pip>=21.3
  - setuptools>=64.0.0
  - git
  - scikit-learn>=1.5.2
  - numpy==2.2.5
  - scipy>=1.7.3
  - pandas>=2.2,<2.3
  - jupyter
  - ipympl
  - matplotlib>=3.4.0
  - seaborn>=0.12.2
  - networkx
  - pillow
  - uvicorn
  - fastapi
  - flask
  - python-dotenv
  - websocket-client
  - pydantic==2.12.4
  - pytest>=4.3.1
  - pytest-cov>=2.6.1
  - pytest-asyncio
  - pre-commit
  - black
  - pip:
    - types-python-dateutil
    - pylinkage
    - pyDOE3
    - nlopt
    - -e .
